name: Generate contribution-snake

on:
  schedule:
    - cron: '0 0 * * *' # executa diariamente à meia-noite (UTC)
  workflow_dispatch: {} # permite rodar manualmente pela aba Actions

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake game from GitHub contribution grid
        uses: Platane/snk@v3
        with:
          github_user_name: ricardolopes2025
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: update contribution snake"
          add: 'dist/github-contribution-grid-snake*.svg'
